server:
  listenaddr: "" # the address to bind on, leave empty to bind on all addresses
  port: 80 # the port for the http server
  alloworigins:
    - "*" # allow all
    # - "http://example.com"
    # - "https://example.com"

database:
  dialect: sqlite3 # other possibilities: mysql, postgres
  connection: mailtify.db
  # if mysql: mailtify:secret@/mailtifydb?charset=utf8&parseTime=True&loc=Local
  # if postgres: host=localhost port=3306 user=mailtify dbname=mailtify password=secret

defaultadmin: # if no admin exists in the database, the default admin is created
  username: # account of the default admin
  password: #

smtp:
  username: # account to connect the smtp server
  password: #
  host: # the smtp server
  port: # port of the smtp server
  from: # mail adress which will send the messages

security:
  tokensize: 16 # max 128, higher is better, but less keyboard-friendly
